### ISSUE TITLE
CM Search is not working

### ISSUE THREAD

**Issue by lgallard** [sciancio/connectionmanager2#58]
I had to change the Gnome version in metadata.json file and all worked except the CM Search. This is a really useful feature, especially when having a lot of connection settings.

This is my environment:
- Debian 8 - Jessie
- Gnome Shell 3.14.4
- Connection Manager 0.8.3

Let me know how can I help.

**Comment by lgallard** [comment]
Same for Ubuntu:

Ubuntu 15.10
Gnome Shell 3.16.4
Connection Manager 0.8.3

**Comment by sciancio** [comment]
Updated to Gnome Shell 3.32.
