### ISSUE TITLE
Not compatible with Gnome 3.24.2

### ISSUE THREAD

**Issue by TheBigFatTony** [sciancio/connectionmanager2#60]
I cannot activate "Connection manager" in Gnome 3.24.2. (Fedora 26)
It tells me "error loading extension". If you require any further information, tell me how I can provide it.

**Comment by omkensey** [comment]
The error is coming from the use of the .quote() method which is not part of the standard and apparently has been removed or disabled in GNOME 3.24.  I got it working again by replacing all calls to the method with the JSON.stringify() function (e.g. foo.quote() becomes JSON.stringify(foo)).

I was going to submit a PR, but I see there's already one that includes that as well as several other changes -- #59.  So if you delete the extension, check out that PR and drop it in `~/.local/share/gnome-shell/extensions/connectionmanager2@ciancio.net/`, the extension should work again.

**Comment by TheBigFatTony** [comment]
yep, that fix worked. thank you and keep up the good work!
