### ISSUE TITLE
CM on Fedora 26, gnome-shell 3.24.2

### ISSUE THREAD

**Issue by BiloxiGeek** [sciancio/connectionmanager2#61]
Just upgraded to Fedora 26 and connection manager in gnome-shell doesn't want to work.  I updated shell-version in metadata.json to match the gnome-shell 3.24 and still no joy.

Looking glass reports this error:
TypeError: Search.SearchProvider is undefined.

Would really like to get this extension working, I use it extensively at home and work.

**Comment by BiloxiGeek** [comment]
Tried reinstalling the extension from scratch and looking glass gives me a different error this time...

TypeError: this.child.Profile.quote is not a function

**Comment by pablaasmo** [comment]
I have the same error. I think it is due to the usage of [String.prototype.quote()]( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/quote)

I am not sure what replace ment to use for the String.prototype.quote() function.
It is used in extension.js and terminal.js

**Comment by BiloxiGeek** [comment]
Late last night I found https://github.com/Silarn/connectionmanager2 which is forked from this project.  It's working nicely on my home F26 system.  But the really odd thing is my F26 system at work did not have the issue at all.  Not gonna argue but it is strange.

**Comment by pablaasmo** [comment]
Using that fork also worked for me. Thanks for that link.

**Comment by plegrand1** [comment]
Using that on my debian sid with gnome-shell 3.26 works fine except the icons size. if i modify  the stylesheet.css i can reduce the size but the big icons come back again and i dont know why ?
May be a solution here ?

**Comment by sciancio** [comment]
Updated to Gnome Shell 3.32
