### ISSUE TITLE
Gnome 3.32 fails to load extension consistently

### ISSUE THREAD

**Issue by sbadger** [sciancio/connectionmanager2#66]
Fails to load after restarts consistently and showing the following in error in looking glass:

TypeError: this.viewSelector.removeSearchProvider is not a function

It seems to load properly after refreshing it from github but on subsequent restarts fails the above error.

FYI, I'm using Fedora 30 beta

**Comment by guyelg** [comment]
+1 , ubuntu 18.06 
gnome 3.28.2

**Comment by sciancio** [comment]
Fix it.
