### ISSUE TITLE
Failed to start in Gnome 44

### ISSUE THREAD

**Issue by pieska** [sciancio/connectionmanager2#74]
it fails to start in fedora 38 with gnome 44.0:

`
gnome-shell[1631]: JS ERROR: Extension connectionmanager2@ciancio.net: TypeError: imports.gi.Gtk.IconTheme.get_default is not a function
                                                           init@/home/pharaoh/.local/share/gnome-shell/extensions/connectionmanager2@ciancio.net/extension.js:351:42
                                                           _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:486:56
                                                           async*loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:394:33
                                                           _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:677:24
                                                           async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:683:48
                                                           _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:718:20
                                                           async*init@resource:///org/gnome/shell/ui/extensionSystem.js:59:14
                                                           _initializeUI@resource:///org/gnome/shell/ui/main.js:309:22
                                                           start@resource:///org/gnome/shell/ui/main.js:186:5
                                                           @resource:///org/gnome/shell/ui/init.js:6:17
`

**Comment by erve-cz** [comment]
On Fedora 38
- try this changes in extension.js :

---
function init(extensionMeta) {
 extensionPath = extensionMeta.path;
 
     //let theme = imports.gi.Gtk.IconTheme.get_default();
     //if (theme != null) {
     let theme = imports.gi.St.IconTheme.new();
     if (theme != null) {
                 theme.append_search_path(extensionPath);
         }
---

and in matadata.json :

"shell-version": [
     "44.1"
   ],

**Comment by pieska** [comment]
thank you, this fixed the issue
